version: 0.2.2.{build}

image: Ubuntu
stack: jdk 11

install:
    - sh: sudo apt-get update
    - sh: sudo apt-get install -y libblosc1

build: off

build_script:
  - ./gradlew build

after_test:
  - ./gradlew distZip

artifacts:
  - path: 'build\distributions\*.zip'
