version: 0.2.3.{build}

environment:
  ARTIFACTORY_USERNAME:
    secure: ZVwlgtk8NtZWeEqpYjR9d8NXeX+xMnuCzgITBKRhtD8=
  ARTIFACTORY_PASSWORD:
    secure: O6ThMzLvtSOPLV0U5yFOkl8G1tFrFOGZEpKI4NSD12c=

image: Ubuntu
stack: jdk 11

install:
  - sh: sudo apt-get update
  - sh: sudo apt-get install -y libblosc1

build: off

build_script:
  - ./gradlew --stacktrace build

after_test:
  - ./gradlew distZip
  - if [ -z "$APPVEYOR_PULL_REQUEST_NUMBER" ]; then ./gradlew -PArtifactoryUserName=${ARTIFACTORY_USERNAME} -PArtifactoryPassword=${ARTIFACTORY_PASSWORD} publish; fi

artifacts:
  - path: 'build\distributions\*.zip'
