---
name: Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    permissions:
      contents: read
    strategy:
      matrix:
        java: [11, 17, 21, 25]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      gradle_commands: --stacktrace build
      ArtifactoryUserName: ${{ secrets.JENKINS_USERNAME }}
      ArtifactoryPassword: ${{ secrets.JENKINS_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: "gradle"
      - name: Install libraries
        run: |
          sudo apt-get install -y libblosc1
      - name: Run with latest Gradle
        if: matrix.java == 25
        run: |
          wget https://services.gradle.org/distributions/gradle-9.2.1-bin.zip
          unzip gradle-9.2.1-bin.zip
          ./gradle-9.2.1/bin/gradle ${{ env.gradle_commands }}
      - name: Run commands
        if: matrix.java != 25
        run: |
          ./gradlew ${{ env.gradle_commands }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bioformats2raw ${{ matrix.java }}
          path: build/distributions/*.zip
          retention-days: 30
      - name: Publish artifacts
        if: github.event_name != 'pull_request' && matrix.java == 11
        run: |
          ./gradlew -PArtifactoryUserName=${ArtifactoryUserName} -PArtifactoryPassword=${ArtifactoryPassword} publish
  release:
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts from build
        uses: actions/download-artifact@v4
        with:
          name: bioformats2raw 11
      - name: List artifacts
        run: ls -R
      - name: Create a GitHub release
        run: gh release create --generate-notes "${GITHUB_REF#refs/tags/}" bioformats2raw-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
